export interface analyticState {
  formData: any
  setOptions: any
  treeList: any
  hasParent: boolean
  checkedKeys: any
  expandedKeys: any
  resetScroll: boolean
  showCheck: boolean
  tableData: any
  tableColumn: any
  dBiz: string
  options: any
  selectVal: string
  activeName: string
  checkedTreeNode: any
  tabActiveId: string
  tabList: any
  defaultProps: any
  pageInfo: any
  tabFileName: string
  checkDropList: any
  checkAllDropList: any
  customList: any
  checkAll: boolean
  isIndeterminate: boolean
  visible: boolean
  addVisible: boolean
  selectionData: any
  dropdownList: any
  loadingShow: boolean

  addData: {
    id: string
    cKmdm: string
    cKmmc: string
    cKmlv: string
    assetCode: string
    assetType: string
    nHldamt: string
    nHldcst: string
    nHldcstLocl: string
    nHldmkv: string
    nHldmkvLocl: string
    nHldvva: string
    nHldvvaL: string
    cCuryCode: string
    nValrate: string
    nPriceCost: string
    nValprice: string
    nCbJzBl: string
    nZcBl: string
    cSubpend: string
    cRights: string
    cIvtClss: string
    cMktCode: string
    cMlAttr: string
  }
}
