/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { NetWorthGetListPostRequest } from '../weiwaiModel';
/**
 * ServiceNetWorthControllerApi - axios parameter creator
 * @export
 */
export const ServiceNetWorthControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/exportExcel
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        netWorthExportExcelPost: async (netWorthGetListPostRequest?: NetWorthGetListPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/netWorth/exportExcel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(netWorthGetListPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/getList
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        netWorthGetListPost: async (netWorthGetListPostRequest?: NetWorthGetListPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/netWorth/getList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(netWorthGetListPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceNetWorthControllerApi - functional programming interface
 * @export
 */
export const ServiceNetWorthControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServiceNetWorthControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/exportExcel
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async netWorthExportExcelPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.netWorthExportExcelPost(netWorthGetListPostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/getList
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async netWorthGetListPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.netWorthGetListPost(netWorthGetListPostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ServiceNetWorthControllerApi - factory interface
 * @export
 */
export const ServiceNetWorthControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServiceNetWorthControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/exportExcel
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        netWorthExportExcelPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.netWorthExportExcelPost(netWorthGetListPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/netWorth/getList
         * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        netWorthGetListPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.netWorthGetListPost(netWorthGetListPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServiceNetWorthControllerApi - object-oriented interface
 * @export
 * @class ServiceNetWorthControllerApi
 * @extends {BaseAPI}
 */
export class ServiceNetWorthControllerApi extends BaseAPI {
    /**
     * 
     * @summary http://127.0.0.1:8080/netWorth/exportExcel
     * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceNetWorthControllerApi
     */
    public netWorthExportExcelPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: AxiosRequestConfig) {
        return ServiceNetWorthControllerApiFp(this.configuration).netWorthExportExcelPost(netWorthGetListPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary http://127.0.0.1:8080/netWorth/getList
     * @param {NetWorthGetListPostRequest} [netWorthGetListPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceNetWorthControllerApi
     */
    public netWorthGetListPost(netWorthGetListPostRequest?: NetWorthGetListPostRequest, options?: AxiosRequestConfig) {
        return ServiceNetWorthControllerApiFp(this.configuration).netWorthGetListPost(netWorthGetListPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
