/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { DataExportExportExcelPostRequest } from '../weiwaiModel';
// @ts-ignore
import { DataExportGetListPostRequest } from '../weiwaiModel';
/**
 * ServiceDataExportControllerApi - axios parameter creator
 * @export
 */
export const ServiceDataExportControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/exportExcel
         * @param {DataExportExportExcelPostRequest} [dataExportExportExcelPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataExportExportExcelPost: async (dataExportExportExcelPostRequest?: DataExportExportExcelPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dataExport/exportExcel`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataExportExportExcelPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/getList
         * @param {DataExportGetListPostRequest} [dataExportGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataExportGetListPost: async (dataExportGetListPostRequest?: DataExportGetListPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dataExport/getList`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dataExportGetListPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ServiceDataExportControllerApi - functional programming interface
 * @export
 */
export const ServiceDataExportControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ServiceDataExportControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/exportExcel
         * @param {DataExportExportExcelPostRequest} [dataExportExportExcelPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataExportExportExcelPost(dataExportExportExcelPostRequest?: DataExportExportExcelPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dataExportExportExcelPost(dataExportExportExcelPostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/getList
         * @param {DataExportGetListPostRequest} [dataExportGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async dataExportGetListPost(dataExportGetListPostRequest?: DataExportGetListPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.dataExportGetListPost(dataExportGetListPostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ServiceDataExportControllerApi - factory interface
 * @export
 */
export const ServiceDataExportControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ServiceDataExportControllerApiFp(configuration)
    return {
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/exportExcel
         * @param {DataExportExportExcelPostRequest} [dataExportExportExcelPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataExportExportExcelPost(dataExportExportExcelPostRequest?: DataExportExportExcelPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.dataExportExportExcelPost(dataExportExportExcelPostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary http://127.0.0.1:8080/dataExport/getList
         * @param {DataExportGetListPostRequest} [dataExportGetListPostRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        dataExportGetListPost(dataExportGetListPostRequest?: DataExportGetListPostRequest, options?: any): AxiosPromise<object> {
            return localVarFp.dataExportGetListPost(dataExportGetListPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ServiceDataExportControllerApi - object-oriented interface
 * @export
 * @class ServiceDataExportControllerApi
 * @extends {BaseAPI}
 */
export class ServiceDataExportControllerApi extends BaseAPI {
    /**
     * 
     * @summary http://127.0.0.1:8080/dataExport/exportExcel
     * @param {DataExportExportExcelPostRequest} [dataExportExportExcelPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceDataExportControllerApi
     */
    public dataExportExportExcelPost(dataExportExportExcelPostRequest?: DataExportExportExcelPostRequest, options?: AxiosRequestConfig) {
        return ServiceDataExportControllerApiFp(this.configuration).dataExportExportExcelPost(dataExportExportExcelPostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary http://127.0.0.1:8080/dataExport/getList
     * @param {DataExportGetListPostRequest} [dataExportGetListPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceDataExportControllerApi
     */
    public dataExportGetListPost(dataExportGetListPostRequest?: DataExportGetListPostRequest, options?: AxiosRequestConfig) {
        return ServiceDataExportControllerApiFp(this.configuration).dataExportGetListPost(dataExportGetListPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
