/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface AssetsBatchAuditPostRequestDataInner
 */
export interface AssetsBatchAuditPostRequestDataInner {
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'startDate'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'endDate'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'pfId'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'pfIdList'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'pfName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'planLicId'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'planLicIdList'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'planName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'startPage'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'pageSize'?: Null;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'orgId'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'orgName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'subjSystem'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'cSubjCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'cSubjName'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'cSubjCodeBz'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'cSubjNameBz'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'subjSystemBz'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'cChecked'?: string;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'checkId'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'checkName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'checkTime'?: Null;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'createPrsn'?: string;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'createPrsnName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'createTime'?: Null;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'mdfyPrsn'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'mdfyTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'isValid'?: string;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'isValidName'?: Null;
    /**
     * 
     * @type {string}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'isDel'?: string;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'isDelName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'nSubjLevel'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'nSubjLevelName'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'checkType'?: Null;
    /**
     * 
     * @type {number}
     * @memberof AssetsBatchAuditPostRequestDataInner
     */
    'row_index'?: number;
}

