/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AssetsBatchAuditPostRequestDataInner } from './assets-batch-audit-post-request-data-inner';

/**
 * 
 * @export
 * @interface AssetsBatchAuditPostRequest
 */
export interface AssetsBatchAuditPostRequest {
    /**
     * 
     * @type {number}
     * @memberof AssetsBatchAuditPostRequest
     */
    'checked': number;
    /**
     * 
     * @type {Array<AssetsBatchAuditPostRequestDataInner>}
     * @memberof AssetsBatchAuditPostRequest
     */
    'data': Array<AssetsBatchAuditPostRequestDataInner>;
}

