/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataExportExportExcelPostRequest
 */
export interface DataExportExportExcelPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DataExportExportExcelPostRequest
     */
    'taskDate': string;
    /**
     * 
     * @type {string}
     * @memberof DataExportExportExcelPostRequest
     */
    'bizDate': string;
    /**
     * 
     * @type {string}
     * @memberof DataExportExportExcelPostRequest
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof DataExportExportExcelPostRequest
     */
    'num': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DataExportExportExcelPostRequest
     */
    'param': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof DataExportExportExcelPostRequest
     */
    'exprortType': number;
}

