/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DataAgingAddPostRequest
 */
export interface DataAgingAddPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'fileType': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'combin': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'delayDay': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'agingRate': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'endTime': string;
    /**
     * 
     * @type {string}
     * @memberof DataAgingAddPostRequest
     */
    'gzDate': string;
}

