/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DicEditPostRequest
 */
export interface DicEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'classId': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'dicClassName': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'classEname': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'keyId': string;
    /**
     * 
     * @type {boolean}
     * @memberof DicEditPostRequest
     */
    'state': boolean;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'stateName': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'keyName': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'keyEname': string;
    /**
     * 
     * @type {string}
     * @memberof DicEditPostRequest
     */
    'memo': string;
}

