/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FilesDeleteFilePostRequest
 */
export interface FilesDeleteFilePostRequest {
    /**
     * 
     * @type {string}
     * @memberof FilesDeleteFilePostRequest
     */
    'rootPath': string;
    /**
     * 
     * @type {string}
     * @memberof FilesDeleteFilePostRequest
     */
    'fileName': string;
    /**
     * 
     * @type {string}
     * @memberof FilesDeleteFilePostRequest
     */
    'id': string;
}

