/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { IndexGetTitleMessagePostRequestData } from './index-get-title-message-post-request-data';

/**
 * 
 * @export
 * @interface IndexGetTitleMessagePostRequest
 */
export interface IndexGetTitleMessagePostRequest {
    /**
     * 
     * @type {number}
     * @memberof IndexGetTitleMessagePostRequest
     */
    'code': number;
    /**
     * 
     * @type {IndexGetTitleMessagePostRequestData}
     * @memberof IndexGetTitleMessagePostRequest
     */
    'data': IndexGetTitleMessagePostRequestData;
    /**
     * 
     * @type {string}
     * @memberof IndexGetTitleMessagePostRequest
     */
    'message': string;
}

