/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface MailRulesFileAnalysisPostRequest
 */
export interface MailRulesFileAnalysisPostRequest {
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'stateId': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'mailTitle': string;
    /**
     * 
     * @type {Null}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'mailContent': Null;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'sendDate': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'addresser': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'fileDir': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'fileName': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'analysisErrorInfo': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'org': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'bizDate': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {Null}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'pfName': Null;
    /**
     * 
     * @type {Null}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'orgId': Null;
    /**
     * 
     * @type {Null}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'fileType': Null;
    /**
     * 
     * @type {Null}
     * @memberof MailRulesFileAnalysisPostRequest
     */
    'fileDate': Null;
}

