/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MailRulesGetMailRulesListPostRequest
 */
export interface MailRulesGetMailRulesListPostRequest {
    /**
     * 
     * @type {string}
     * @memberof MailRulesGetMailRulesListPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof MailRulesGetMailRulesListPostRequest
     */
    'parsingRules': string;
    /**
     * 
     * @type {number}
     * @memberof MailRulesGetMailRulesListPostRequest
     */
    'startPage': number;
    /**
     * 
     * @type {number}
     * @memberof MailRulesGetMailRulesListPostRequest
     */
    'pageSize': number;
    /**
     * 
     * @type {string}
     * @memberof MailRulesGetMailRulesListPostRequest
     */
    'wfType': string;
}

