/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MailSearchPostRequest
 */
export interface MailSearchPostRequest {
    /**
     * 
     * @type {number}
     * @memberof MailSearchPostRequest
     */
    'startPage': number;
    /**
     * 
     * @type {number}
     * @memberof MailSearchPostRequest
     */
    'pageSize': number;
    /**
     * 
     * @type {string}
     * @memberof MailSearchPostRequest
     */
    'beginDate': string;
    /**
     * 
     * @type {string}
     * @memberof MailSearchPostRequest
     */
    'endDate': string;
    /**
     * 
     * @type {string}
     * @memberof MailSearchPostRequest
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof MailSearchPostRequest
     */
    'mailContent': string;
    /**
     * 
     * @type {string}
     * @memberof MailSearchPostRequest
     */
    'orgId': string;
}

