/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MasterDataManagementEditPostRequestInfoExtsInner } from './master-data-management-edit-post-request-info-exts-inner';

/**
 * 
 * @export
 * @interface MasterDataManagementEditPostRequest
 */
export interface MasterDataManagementEditPostRequest {
    /**
     * 
     * @type {boolean}
     * @memberof MasterDataManagementEditPostRequest
     */
    'checked': boolean;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'createPrsn': string;
    /**
     * 
     * @type {number}
     * @memberof MasterDataManagementEditPostRequest
     */
    'createTime': number;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'id': string;
    /**
     * 
     * @type {Array<MasterDataManagementEditPostRequestInfoExtsInner>}
     * @memberof MasterDataManagementEditPostRequest
     */
    'infoExts': Array<MasterDataManagementEditPostRequestInfoExtsInner>;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'note1': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'note2': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'orgCode': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'orgName': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequest
     */
    'orgSname': string;
}

