/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MasterDataManagementEditPostRequestInfoExtsInner
 */
export interface MasterDataManagementEditPostRequestInfoExtsInner {
    /**
     * 
     * @type {number}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'index': number;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'extend': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'extendVal': string;
    /**
     * 
     * @type {number}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'orgCode': string;
    /**
     * 
     * @type {string}
     * @memberof MasterDataManagementEditPostRequestInfoExtsInner
     */
    'remarks': string;
}

