/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgIndexStatePostRequest
 */
export interface OrgIndexStatePostRequest {
    /**
     * 
     * @type {string}
     * @memberof OrgIndexStatePostRequest
     */
    'state': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrgIndexStatePostRequest
     */
    'ids': Array<string>;
}

