/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgSubjTypeEditPostRequest
 */
export interface OrgSubjTypeEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'assetType': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'assetTypena': string;
    /**
     * 
     * @type {number}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'cChecked': number;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'cSubjCode': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'cSubjName': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'checkId': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'checkName': string;
    /**
     * 
     * @type {number}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'checkTime': number;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'createPrsn': string;
    /**
     * 
     * @type {number}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'createTime': number;
    /**
     * 
     * @type {number}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'orgName': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'subjCode': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'subjName': string;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'subjSystem': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'infoExts': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof OrgSubjTypeEditPostRequest
     */
    'remarke': string;
}

