/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrgIndexEditPostRequest
 */
export interface OrgIndexEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'cindexSource': string;
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'cindexCode': string;
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'valid': string;
    /**
     * 
     * @type {string}
     * @memberof OrgIndexEditPostRequest
     */
    'cindexName': string;
}

