/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OutAssetMappingOutAssetMappingSavePostRequest
 */
export interface OutAssetMappingOutAssetMappingSavePostRequest {
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'assetName': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'assetCode': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'mktCode': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'sAssetCode': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'sAssetName': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'sAssetType': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'sMktCode': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof OutAssetMappingOutAssetMappingSavePostRequest
     */
    'assetType': string;
}

