/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SourceAnalysis2ExcutePostRequestDataInner } from './source-analysis2-excute-post-request-data-inner';
// May contain unused imports in some cases
// @ts-ignore
import { SourceAnalysis2ExcutePostRequestRow } from './source-analysis2-excute-post-request-row';

/**
 * 
 * @export
 * @interface SourceAnalysis2ExcutePostRequest
 */
export interface SourceAnalysis2ExcutePostRequest {
    /**
     * 
     * @type {SourceAnalysis2ExcutePostRequestRow}
     * @memberof SourceAnalysis2ExcutePostRequest
     */
    'row': SourceAnalysis2ExcutePostRequestRow;
    /**
     * 
     * @type {Array<SourceAnalysis2ExcutePostRequestDataInner>}
     * @memberof SourceAnalysis2ExcutePostRequest
     */
    'data': Array<SourceAnalysis2ExcutePostRequestDataInner>;
}

