/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface SourceAnalysis2ExcutePostRequestDataInner
 */
export interface SourceAnalysis2ExcutePostRequestDataInner {
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    '20230321'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    '20230322'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    '20230323'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'pfName'?: string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'agingRate'?: Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'pfId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'bizDate'?: string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'endTime'?: Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'delayDay'?: string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestDataInner
     */
    'orgId'?: string;
}

