/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface SourceAnalysis2ConfirmPostRequest
 */
export interface SourceAnalysis2ConfirmPostRequest {
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'processNm': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'bizDate': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'state': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'stateId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'wfId': string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'userID': Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'sourceId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'timeMark': string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'lastWfId': Null;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'lastWfState': Null;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'marketCode': Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'taskDate': string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'wfIds': Null;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'pfName': Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ConfirmPostRequest
     */
    'id': string;
}

