/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface SourceAnalysis2ExcutePostRequestRow
 */
export interface SourceAnalysis2ExcutePostRequestRow {
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    '20230321': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    '20230322': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    '20230323': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'pfName': string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'agingRate': Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'bizDate': string;
    /**
     * 
     * @type {Null}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'endTime': Null;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'delayDay': string;
    /**
     * 
     * @type {string}
     * @memberof SourceAnalysis2ExcutePostRequestRow
     */
    'orgId': string;
}

