/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SpecialStrategySpecialStrategySavePostRequestInfoExtsInner
 */
export interface SpecialStrategySpecialStrategySavePostRequestInfoExtsInner {
    /**
     * 
     * @type {number}
     * @memberof SpecialStrategySpecialStrategySavePostRequestInfoExtsInner
     */
    'index': number;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequestInfoExtsInner
     */
    'extField': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequestInfoExtsInner
     */
    'extFieldValue': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequestInfoExtsInner
     */
    'extFieldNote': string;
}

