/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SpecialStrategySpecialStrategySavePostRequestInfoExtsInner } from './special-strategy-special-strategy-save-post-request-info-exts-inner';

/**
 * 
 * @export
 * @interface SpecialStrategySpecialStrategySavePostRequest
 */
export interface SpecialStrategySpecialStrategySavePostRequest {
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'pfName': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'mngrId': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'trustmngrId': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'posState': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'assetType': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'chgDate': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'endDate': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'investMgr': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'investDepName': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'investDep': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'investWay': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'marketCode': string;
    /**
     * 
     * @type {string}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'marketCode2': string;
    /**
     * 
     * @type {Array<SpecialStrategySpecialStrategySavePostRequestInfoExtsInner>}
     * @memberof SpecialStrategySpecialStrategySavePostRequest
     */
    'infoExts': Array<SpecialStrategySpecialStrategySavePostRequestInfoExtsInner>;
}

