/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubjectSubjectUpdatePostRequestInner
 */
export interface SubjectSubjectUpdatePostRequestInner {
    /**
     * 
     * @type {number}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'cChecked'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'cCuryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'cSubjCls'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'cSubjCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'cSubjName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'checkId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'checkTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'createPrsn'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'createTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'isDetail'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'isSum'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'isV'?: string;
    /**
     * 
     * @type {number}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'isValid'?: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'mapType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'mdfyPrsn'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'mdfyTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'nSubjLevel'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'nSubjLevelName'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'nWay'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'orgId'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'pSubjCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'subjSystem'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SubjectSubjectUpdatePostRequestInner
     */
    'isUpdate'?: boolean;
}

