/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TaskLogGetListPostRequest
 */
export interface TaskLogGetListPostRequest {
    /**
     * 
     * @type {number}
     * @memberof TaskLogGetListPostRequest
     */
    'startPage': number;
    /**
     * 
     * @type {number}
     * @memberof TaskLogGetListPostRequest
     */
    'pageSize': number;
    /**
     * 
     * @type {string}
     * @memberof TaskLogGetListPostRequest
     */
    'bizDate': string;
    /**
     * 
     * @type {string}
     * @memberof TaskLogGetListPostRequest
     */
    'detailId': string;
    /**
     * 
     * @type {string}
     * @memberof TaskLogGetListPostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof TaskLogGetListPostRequest
     */
    'state': string;
}

