/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsersEditPostRequest
 */
export interface UsersEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'orgName': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'contacts': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'tel': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'tel1': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'isValid': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'validName': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'job': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'mail': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'memo': string;
    /**
     * 
     * @type {string}
     * @memberof UsersEditPostRequest
     */
    'createTime': string;
}

