/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface ValDataLockLockValPostRequestDataInner
 */
export interface ValDataLockLockValPostRequestDataInner {
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'pfId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'pfName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'vlaDate'?: string;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'netDate'?: Null;
    /**
     * 
     * @type {number}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'delState'?: number;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'delStateName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'lockUser'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'isUptoDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'isUptoDateName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'lockTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'lockState'?: string;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'lockStateName'?: string;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'dateType'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'createPrsn'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'mdfyPrsn'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'isValid'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'bizDate'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'filePath'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'fileDir'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'orgId'?: Null;
    /**
     * 
     * @type {string}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'taskDate'?: string;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'isUptoDate2'?: Null;
    /**
     * 
     * @type {Null}
     * @memberof ValDataLockLockValPostRequestDataInner
     */
    'errorWf'?: Null;
}

