/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ValDataLockLockValPostRequestDataInner } from './val-data-lock-lock-val-post-request-data-inner';

/**
 * 
 * @export
 * @interface ValDataLockLockValPostRequest
 */
export interface ValDataLockLockValPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ValDataLockLockValPostRequest
     */
    'state': number;
    /**
     * 
     * @type {Array<ValDataLockLockValPostRequestDataInner>}
     * @memberof ValDataLockLockValPostRequest
     */
    'data': Array<ValDataLockLockValPostRequestDataInner>;
}

