/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ValuationConfigAddPostRequest
 */
export interface ValuationConfigAddPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'fileTag': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'tagCode': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'colNum': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'tagNum': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'valid': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'tagName': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'fileType': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'colName': string;
    /**
     * 
     * @type {string}
     * @memberof ValuationConfigAddPostRequest
     */
    'tagTable': string;
}

