/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface ValueNewEditPostRequest
 */
export interface ValueNewEditPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'orgId': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'pfId': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'dBiz': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cKmdm': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cKmmc': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'fKmbmP': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'fPmmP': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nHldamt': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nHldcst': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nHldcstLocl': string;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'nHldmkv': Null;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nHldmkvLocl': string;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'nHldvva': Null;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nHldvvaL': string;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'cCuryCode': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'nValrate': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'nPriceCost': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'nValprice': Null;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nCbJzBl': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nSzJzBl': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'nZcBl': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cSubpend': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cRights': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cIvtClss': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cMktCode': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cMlAttr': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'sourceType': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'checkId': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'cChecked': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'checkTime': string;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'createPrsn': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'createTime': Null;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'mdfyPrsn': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'mdfyTime': string;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'sourceId': string;
    /**
     * 
     * @type {number}
     * @memberof ValueNewEditPostRequest
     */
    'cKmlv': number;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'children': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'assetCode': Null;
    /**
     * 
     * @type {Null}
     * @memberof ValueNewEditPostRequest
     */
    'assetType': Null;
    /**
     * 
     * @type {string}
     * @memberof ValueNewEditPostRequest
     */
    'id': string;
}

