/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowAddPostRequest
 */
export interface WorkflowAddPostRequest {
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfMode': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfName': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfId': string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowAddPostRequest
     */
    'maxRuntime': number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfDatatype': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfAttr': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowAddPostRequest
     */
    'wfDesc': string;
}

