/* tslint:disable */
/* eslint-disable */
/**
 * 委外
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Null } from './null';

/**
 * 
 * @export
 * @interface WorkflowQueryPostRequest
 */
export interface WorkflowQueryPostRequest {
    /**
     * 
     * @type {number}
     * @memberof WorkflowQueryPostRequest
     */
    'startPage': number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowQueryPostRequest
     */
    'pageSize': number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowQueryPostRequest
     */
    'wfId': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowQueryPostRequest
     */
    'wfName': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowQueryPostRequest
     */
    'wfDatatype': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowQueryPostRequest
     */
    'wfAttr': string;
    /**
     * 
     * @type {Null}
     * @memberof WorkflowQueryPostRequest
     */
    'sta': Null;
}

